
export const LOFI_SONGS = [
    {
        id: 1,
        type: "lofi",
        name: "Tại Vì Sao",
        singer: " ❦ MCK",
        path: "./assets/music/song13.mp3",
        img: "./assets/img/MCk.jpg",
    },
    {
        id: 2,
        type: "lofi",
        name: "Cuộc Gọi Đêm",
        singer: " ❦ Uyên Tố...",
        path: "./assets/music/song12.mp3",
        img: "./assets/img/UyenTo.jpg",
    },
    {
        id: 3,
        type: "lofi",
        name: "Crush 2",
        singer: " ❦ W/n...",
        path: "./assets/music/song10.mp3",
        img: "./assets/img/Wn.jpg",
    },
    {
        id: 4,
        type: "lofi",
        name: "Your Smile",
        singer: " ❦ Obito ft hnhngan",
        path: "./assets/music/song5.mp3",
        img: "./assets/img/hnhngan.jpg",
    },
    {
        id: 5,
        type: "lofi",
        name: "Anh Biết",
        singer: " ❦ Xám x D.Blue",
        path: "./assets/music/song11.mp3",
        img: "./assets/img/Xam-1-scaled.jpg",
    },
    {
        id: 6,
        type: "lofi",
        name: "Chìm Sâu",
        singer: " ❦ Tu Salmon",
        path: "./assets/music/song2.mp3",
        img: "./assets/img/TuSalmon.jpg",
    },
    {
        id: 7,
        type: "lofi",
        name: "Mascara",
        singer: " ❦ Chillies",
        path: "./assets/music/song4.mp3",
        img: "./assets/img/Chillies.jpg",
    },
    {
        id: 8,
        type: "lofi",
        name: "Xe Đạp",
        singer: " ❦ Charles",
        path: "./assets/music/song7.mp3",
        img: "./assets/img/Charles.jpg",
    },
    {
        id: 9,
        type: "lofi",
        name: "20 Năm Ở Thế Giới",
        singer: " ❦ Thịnh Suy",
        path: "./assets/music/song8.mp3",
        img: "./assets/img/ThinhSuy.jpg",
    },
    {
        id: 10,
        type: "lofi",
        name: "Có Hẹn Với Thanh Xuân",
        singer: " ❦ Monstar",
        path: "./assets/music/song9.mp3",
        img: "./assets/img/Monstar.jpg",
    },
    {
        id: 11,
        type: "lofi",
        name: "Tiny love",
        singer: " ❦ Thịnh Suy",
        path: "./assets/music/song1.mp3",
        img: "./assets/img/ThinhSuy.jpg",
    },
    {
        id: 12,
        type: "lofi",
        name: "Mơ",
        singer: " ❦ Vũ Cát Tường",
        path: "./assets/music/song6.mp3",
        img: "./assets/img/VuCatTuong.jpg",
    },

    {
        id: 13,
        type: "lofi",
        name: "Tình yêu xanh lá",
        singer: " ❦ Thịnh Suy",
        path: "./assets/music/song3.mp3",
        img: "./assets/img/ThinhSuy.jpg",
    },
]

export const SPEED_UP_SONGS = [
    {
        id: 14,
        type: "speed_up",
        name: "Anh Đã Lạc Vào",
        singer: " ❦ Green",
        path: "./assets/music/anh-da-lac-vao-green.mp3",
        img: "./assets/img/cat1.jpg",
    },
    {
        id: 15,
        type: "speed_up",
        name: "Chỉ Cần Có Em",
        singer: " ❦ Twenty, Darki",
        path: "./assets/music/chi-can-co-em-twenty-darki.mp3",
        img: "./assets/img/cat2.jpg",
    },
    {
        id: 16,
        type: "speed_up",
        name: "Chỉ Cần Có Em",
        singer: " ❦ DMean",
        path: "./assets/music/iu-em-roi-tinh-sao-dmean.mp3",
        img: "./assets/img/cat3.jpg",
    },
    {
        id: 17,
        type: "speed_up",
        name: "Matchanah",
        singer: " ❦ Híu x Bâu",
        path: "./assets/music/matchanah-hiu-bau.mp3",
        img: "./assets/img/cat4.jpg",
    },
    {
        id: 18,
        type: "speed_up",
        name: "Miên Man",
        singer: " ❦ Minh Huy",
        path: "./assets/music/mien-man-minhhuy.mp3",
        img: "./assets/img/cat5.jpg",
    },
    {
        id: 19,
        type: "speed_up",
        name: "Mộng Mơ",
        singer: " ❦ RedT",
        path: "./assets/music/mong-mo-redt.mp3",
        img: "./assets/img/cat6.jpg",
    },
    {
        id: 20,
        type: "speed_up",
        name: "Nụ Cười Em Là Nắng",
        singer: " ❦ Green",
        path: "./assets/music/nu-cuoi-em-la-nang-green.mp3",
        img: "./assets/img/cat7.jpg",
    },
    {
        id: 21,
        type: "speed_up",
        name: "Phỏng Lài Em",
        singer: "❦ Daduc, Dipper",
        path: "./assets/music/phong-lai-em-daduc-dipper.mp3",
        img: "./assets/img/cat8.jpg",
    },
    {
        id: 22,
        type: "speed_up",
        name: "Say Đắm Trong Lần Đầu",
        singer: "❦ Winno",
        path: "./assets/music/say-dam-trong-lan-dau-winno.mp3",
        img: "./assets/img/cat9.jpg",
    },
    {
        id: 23,
        type: "speed_up",
        name: "Tình Cờ Yêu Em",
        singer: "❦ Linh Thộn, Kuun Đức Nam",
        path: "./assets/music/tinh-co-yeu-em.mp3",
        img: "./assets/img/cat10.jpg",
    },
    {
        id: 24,
        type: "speed_up",
        name: "Tình Đơn Phương",
        singer: "❦ Nguyên, Koo",
        path: "./assets/music/tinh-don-phuong-nguyen-koo.mp3",
        img: "./assets/img/cat11.jpg",
    },
    {
        id: 25,
        type: "speed_up",
        name: "Từng Quen",
        singer: "❦ Wren EVans",
        path: "./assets/music/tung-quen-wren-evans.mp3",
        img: "./assets/img/cat12.jpg",
    },
    {
        id: 26,
        type: "speed_up",
        name: "Unfollow",
        singer: "❦ Freaky",
        path: "./assets/music/unfollow-freaky.mp3",
        img: "./assets/img/cat13.jpg",
    },
    {
        id: 27,
        type: "speed_up",
        name: "Gu",
        singer: "❦ Freaky, Seachains",
        path: "./assets/music/gu-freaky-seachains.mp3",
        img: "./assets/img/cat2.jpg",
    },
]

export const THUMBNS = [
    "./assets/img/thumbs/thumb-2.gif",
    "./assets/img/thumbs/thumb-3.gif",
    "./assets/img/thumbs/thumb-4.jpg",
    "./assets/img/thumbs/thumb-5.gif",
    "./assets/img/thumbs/thumb-6.gif",
]
